### ISSUE TITLE
ModuleNotFoundError: No module named 'crispy_forms'

### ISSUE THREAD

**Issue by nguyenbh1507** [JohnKiguru/Working-with-matplotlib-and-Django#1]
I just clone this repo and run
```bash
python manage.py runserver
```
Then it throws an error `ModuleNotFoundError: No module named 'crispy_forms'`
It's clear that `crispy_forms` was not implemented as `sales`.
Please upload source code for `crispy_forms`.
Thank you very much.

**Comment by JohnKiguru** [comment]
You need to install  django-crispy-forms by running pip install django-crispy-forms...

**Comment by nguyenbh1507** [comment]
@JohnKiguru thank you for your replying.
I installed it and change sales/urls.py a bit (line 6)
It runs properly.
